# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from webdriver_manager.chrome import ChromeDriverManager
from pathlib import Path
from datetime import date
from constants import GlobalConstants


class TestSatinalma():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
    self.vars = {}

    self.folderPath=str(f"Sauce Fatura Bilgileri")#satın alma sonrası eksan görüntüsü
    Path(self.folderPath).mkdir(exist_ok=True) 
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def WaitForElementVisibility(self,locator,timeout=5):
    WebDriverWait(self.driver,timeout).until(ec.visibility_of_element_located(locator))
  
  def test_satinalma(self):
    self.driver.get(GlobalConstants.URL)
    self.driver.maximize_window()

    self.WaitForElementVisibility((By.CSS_SELECTOR, "*[data-test=\"username\"]"))
    username=self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]")
    username.click()
    username.send_keys("standard_user")
    self.WaitForElementVisibility((By.CSS_SELECTOR, "*[data-test=\"password\"]"))
    password=self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]")
    password.click()
    password.send_keys("secret_sauce")
    
    loginBtn = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]")
    loginBtn.click()
    
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"product_sort_container\"]")
    LtoH = dropdown.find_element(By.CSS_SELECTOR, "*:nth-child(2)")
    LtoH.click()

    #add item 
    self.WaitForElementVisibility((By.CSS_SELECTOR,"*[data-test=\"add-to-cart-sauce-labs-onesie\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-onesie\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-test.allthethings()-t-shirt-(red)\"]").click()

    sepet= self.driver.find_element(By.LINK_TEXT, "4")
    sepet.click()

    #remove item
    self.WaitForElementVisibility((By.CSS_SELECTOR,"*[data-test=\"remove-sauce-labs-bolt-t-shirt\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-bolt-t-shirt\"]").click()
    
    self.WaitForElementVisibility((By.CSS_SELECTOR,"*[data-test=\"checkout\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"checkout\"]").click()

    self.WaitForElementVisibility((By.CSS_SELECTOR,"*[data-test=\"firstName\"]"))
    firstname = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]")
    firstname.click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").send_keys(GlobalConstants.NAME)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").send_keys(GlobalConstants.SURNAME)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").send_keys(GlobalConstants.ZIPCODE)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"continue\"]").click()

    self.WaitForElementVisibility((By.CSS_SELECTOR,"*[data-test=\"finish\"]"))
    self.driver.save_screenshot(f"{self.folderPath}/Checkout-Overview -{date.today()}.png")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"finish\"]").click()

    self.WaitForElementVisibility((By.CSS_SELECTOR,".complete-text"))
    assert self.driver.find_element(By.CSS_SELECTOR, ".complete-text").text == GlobalConstants.COMPLETE
    
    #geri dönüş ve Logout
    self.WaitForElementVisibility((By.CSS_SELECTOR,"*[data-test=\"back-to-products\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"back-to-products\"]").click()
    self.driver.find_element(By.ID, "react-burger-menu-btn").click()
    self.WaitForElementVisibility((By.ID,"logout_sidebar_link"))
    self.driver.find_element(By.ID, "logout_sidebar_link").click()

    #logout sonrası Login sayfasına dönüldü mü?
    self.WaitForElementVisibility((By.CSS_SELECTOR,"*[data-test=\"login-button\"]"))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "*[data-test=\"login-button\"]")
    assert len(elements) > 0
    self.driver.close()
  
